### PR TITLE
add enable and disable to custom device

### PR DESCRIPTION
**Pull request by papowerNI**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-ballard-arinc429-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Add RTM option to enable and disable this custom device in the System Explorer and using the Scripting API.
image
image

### Why should this Pull Request be merged?

Fixes issue #173 

### What testing has been done?
1) Ran automated tests for Scripting API and added a couple of tests for disable case:
image

2) Added automated test to deploy a custom device that is disabled:
image

2) Manually enabled and disabled the device.  When custom device is enabled, a loopback test successfully reads and writes PSI values:
working enabled rtm

When custom device is disabled, the loopback test does nothing, no reads or writes:
working disabled rtm

### CODE REVIEW

**Comment by rtzoeller** [comment]
Thanks for adding this! A few things:

- [ ] Can you update the PR description to check this box?
image

- [ ] Ideally there would be a way to enable and disable the custom device using the scripting API. IMO this is not a requirement for this PR, but it'd be appreciated. It looks like we had separate VIs for enabling and disabling items in the Routing and Faulting custom device.
- [ ] The addition of a "disabled" state breaks scripting API VIs which look for the custom device by GUID, such as `Find Ballard ARINC-429 Custom Devices.vi`. You should be able to find global references to the GUID, and update their logic accordingly. Having a test that these VIs work for disabled instances of the custom device would be good too.

**Comment by dbendele** [comment]
- [ ] Can you verify that you can deploy a project with this custom device even if this custom device has an error (i.e. the user has not specified a hardware configuration file)?

**Review by dbendele — APPROVED** [review]
pending Ryan's requested changes and...

This or a following PR:
 - [x] automated test to verify that you can deploy a project with disabled custom device (PP: added in commit 4)

**Review by buckd — COMMENTED** [review]
- [ ] `Implementation.lvlib:EnableDisable RTM.vi` should use the scripting VIs for enabling/disabling things so everything goes through the same code path. You can force a redraw of System Explorer using `NI VeriStand - Highlight Node in System Explorer.vi`, but dynamic buttons are not always redrawn. You can look at how we did this for Routing and Faulting in `Source/Routing and Faulting/System Explorer/Enable Disable Routing Channel RTM.vi`.
- [x] There is no reason to re-enable the custom device at the end of `test Find Disabled Custom Devices.vi` or `test Get Owning Disabled Custom Device.vi`. The system definition is not saved at the end of these tests, so it will start in the same state for each test.
- [x] Don't add these types of messages as errors in your tests. These messages are always displayed, even when the test passes.
image
- [ ] In `Disabled Custom Device.lvclass` there is no need to save the custom device reference in the class private data. It is not used in the test. Instead, save the system definition path and use that in the test instead of having the path hard-coded in `setUp.vi` and the test VI.

**Comment by papowerNI** [comment]
@buckd 
> * You can force a redraw of System Explorer using `NI VeriStand - Highlight Node in System Explorer.vi`, but dynamic buttons are not always redrawn. You can look at how we did this for Routing and Faulting in `Source/Routing and Faulting/System Explorer/Enable Disable Routing Channel RTM.vi`.

The System Explorer seems to be redrawn reliably if I set **Refresh System Explorer Tree?** to **True** on `NI Veristand - Set Item GUID.vi` when using the RTM; are there situations where that doesn't redraw reliably that I haven't seen?  I'm hesitant to add in the uses of `NI Veristand - Highlight Node in System Explorer` that are used in Routing and Faulting because it triples the length of the "busy" spinning cursor icon after I select Disable/Enable.

**Comment by buckd** [comment]
> The System Explorer seems to be redrawn reliably if I set **Refresh System Explorer Tree?** to **True** on `NI Veristand - Set Item GUID.vi` when using the RTM

That's fine if we put that in the scripting API calls and no error comes from using the API outside of System Explorer.

**Review by buckd — APPROVED** [review]
There is no need for `Check for Disabled Devices before Compile.vi`. The scripting API already has `Check If Custom Device Enabled.vi`. Just use that VI instead.

**Comment by papowerNI** [comment]
> There is no need for Check for Disabled Devices before Compile.vi. The scripting API already has Check If Custom Device Enabled.vi. Just use that VI instead.

As we discussed offline, I am going to change Check for Disabled Devices before Compile.vi to be a wrapper of the Scripting API call, since we don't currently expose the Scripting API in the System Explorer or Engine lvlibps

**Pull request merged**
