### PR TITLE
Expand logging configuration to include the file name and data word format

### PR DESCRIPTION
**Pull request by rtzoeller**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-ballard-arinc429-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

All users to configure a file name (including an optional timestamp), as well as the format of the logged data word.

Define unit tests around custom Linux path manipulation.

### Why should this Pull Request be merged?

We want users to be able to customize the log file name in a similar way to the Embedded Data Logger.

### What testing has been done?

Hand testing of deployed functionality. Added unit tests for path manipulation.

### CODE REVIEW

**Comment by rtzoeller** [comment]
I do not currently have any system tests that exercise this functionality, but intend to add them (either in this PR or a subsequent one). @buckd please let me know if you want the tests submitted as part of this PR.

**Comment by buckd** [comment]
> I do not currently have any system tests that exercise this functionality, but intend to add them (either in this PR or a subsequent one). @buckd please let me know if you want the tests submitted as part of this PR.

A separate PR is fine.

**Review by buckd — COMMENTED** [review]
- [x] The new scripting VIs need better icons, even if it is just text for now. The only thing they show is get or set, not which item they are accessing.

I'll leave this decision up to you - `Data Word Format.ctl` - You can actually specify the format string as the value for each of the strings so you don't need the case structure (or ever make updates if new formats are added) in `Format Word for CSV.vi`. I've done this before and it's pretty useful.
The one downside I see is, since we're storing this string in the sysdef, you wouldn't see the selected string in the XML, only the format string with the current way the scripting VIs are written. You could work around this by using the **StringsAndValues** property node to convert the value back to the display string before writing and vice versa, but that may be more trouble than it is worth.

**Comment by rtzoeller** [comment]
I'm going to leave the format string handling as-is for now, but I do think something like this (which would allow a sufficiently motivated user to specify a custom format string entirely) is worth considering for other protocols. ARINC-429's 32-bit format doesn't leave too much flexibility in how the values are represented, so I don't think it's worthwhile in this case.

**Review by buckd — APPROVED** [review]

**Pull request merged**
