### PR TITLE
Add timeout to trigger read to match data read, to prevent multiple Acyclic Tx per trigger

### LINKED ISSUE #195: Acyclic Tx labels sent twice on each trigger
**Describe the bug**
Acyclic messages are sent on a trigger rather than continuously at a specified rate. Given that acyclic messages are sent on a trigger, users expect that the acyclic labels are only sent once per trigger event.

**To Reproduce**
1. Open a new default project in VeriStand.
2. Add a Ballard ARINC 429 custom device to the project.
3. Specify the attached configuration files.
4. Enable logging in the custom device.
5. Deploy.
6. Trigger each loopback Tx label.
7. Disconnect and inspect the generated log file.
8. Note that each triggered acyclic label was received and logged twice.
>time stamp,channel,label,sdi,data word
23.226483,3,7,0,3758147591
23.326562,3,7,0,3758147591
24.226202,3,8,0,1610664968
24.326282,3,8,0,1610664968
25.625882,3,23,0,1610666007
25.726322,3,23,0,1610666007
27.225722,3,24,0,3758150680
27.326162,3,24,0,3758150680

**Expected behavior**
One trigger = one transmit.
[Configuration Files.zip](https://github.com/ni/niveristand-ballard-arinc429-custom-device/files/7671608/Configuration.Files.zip)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux RT
 - Version: base image = 21.0

**Additional context**

### PR DESCRIPTION
**Pull request by papowerNI**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-ballard-arinc429-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Add a timeout to the Data Access Engine ReadWrite call that reads triggers, to match the timeout of the Read call for the associated data, to prevent the trigger from being read multiple times.

Also adds a test that validates the acyclic behavior for the future.

### Why should this Pull Request be merged?

Fixes #195 

### What testing has been done?

Ran VI Tester tests, manually logged data and checked, no more duplicate logs:
image
Added a system test that validates this, and ran it before and after my targeted change (run without changes on the right):
image

Also ran some manual performance tests, no noticeable change to performance using a stress test xml from Karl:

Without Changes:
no changes

With Changes:
pauls changes

### CODE REVIEW

**Comment by buckd** [comment]
It's interesting that this change fixes the problem. I'm not sure if it has to do with how LabVIEW manages FIFOs with 0 timeout or something else. @papowerNI can you run a couple modified tests for me. I'd like to see how it behaves when the PCL rate is changed. Since we're scripting all of these tests, I believe they are all running at 100 Hz. Can you try something like 500 Hz and 50 Hz and see if everything still works?

**Comment by papowerNI** [comment]
@buckd I increased the timeout to exceed the expected maximum of the PCL loop duration (1000ms) and I switched to using the atomic readwrite method as you mentioned, and the duplication no longer occurs even at 10k or 1Hz PCL rates:
image

**Review by buckd — APPROVED** [review]
Thanks for indulging my curiosity on this fix. It was a little winding to get to the solution.

This is ok for now. You may want to revisit when you're doing performance testing since this implementation will continue to run the encoding portion for every label even if there are no triggers. We could probably bypass all of this if triggers are invalid, but we'll see what comes from your evaluation.
image

**Comment by buckd** [comment]
@papowerNI Can you file an issue on the [template repo](https://github.com/ni/niveristand-communications-bus-template) to incorporate this change into the base template so we don't hit this same issue in the future?

**Pull request merged**
