### PR TITLE
Bump mutation version to 1.1.0 and mutate to add Logging section

### PR DESCRIPTION
**Pull request by rtzoeller**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-ballard-arinc429-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Introduce mutation logic to add the Logging section to existing system definitions.

### Why should this Pull Request be merged?

System definitions with an older version of the custom device fail to deploy if the Logging section is missing.

### What testing has been done?

Loaded an existing system definition and confirmed it the Logging section was added and the custom device version was updated.

### CODE REVIEW

**Review by dbendele — COMMENTED** [review]
As part of this PR:
 - [x] Write a mutation test
 - [x] Will you update existing system definitions in the repo?

**Review by buckd — APPROVED** [review]
I agree with the request for a mutation test.

I don't think we need to update the existing system definitions. This shouldn't be a breaking mutation as the engine should just ignore any logging configuration that isn't there.

**Comment by rtzoeller** [comment]
@buckd we currently will need to update the system definitions, as we otherwise fail when we attempt to read properties on the Logging section which doesn't exist. 

I was conflicted on this, but unless we plan to guarantee deployment of un-mutated system definitions moving forward (and test it), I'd rather not put in any work to support this use case. It sets a bad precedent relative to other custom devices like SEECD which do require the system definition be re-saved.

**Comment by rtzoeller** [comment]
@dbendele I thought you had previously mentioned all test system definitions were dynamically generated? Is that not true?

**Comment by dbendele** [comment]
> @dbendele I thought you had previously mentioned all test system definitions were dynamically generated? Is that not true?

There are a handful of system definition files in this repo.

**Comment by rtzoeller** [comment]
FYI @dbendele, I only updated the sysdefs for the system tests. There are some sysdefs in the unit tests folder which should be updated at some point, but they're so old it's painful to do so and I didn't want to hold this PR up (e.g. the parameters file isn't even recognized as being valid anymore).

**Pull request merged**
