### PR TITLE
Add Logging palette

### PR DESCRIPTION
**Pull request by rtzoeller**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-ballard-arinc429-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Add Logging section to custom device palettes. Correct VI descriptions.

Fix all other palettes, which broke in #180.

### Why should this Pull Request be merged?

We want the logging configuration to be scriptable.

### What testing has been done?

Built scripting API locally and inspected palettes.

image

### CODE REVIEW

**Review by dbendele — CHANGES_REQUESTED** [review]
- [x] Please make primary inputs required on Set * Logging VIs
 - [x] Please make default word format Decimal (as opposed to empty)
 - [ ] `Ballard ARINC 429 Scripting.lvlib--Find Logging Section.vi` should have a **found?** output. 
    - [ ] Since this is a required section (and we require resave according to conversation in #186), should we return an error if `Logging` section not found?

**Comment by rtzoeller** [comment]
@dbendele I do not believe `Find Logging Section.vi` should have a `found?` output. I'm happy to discuss if a better error should be set than just returning an invalid item ref, but having a `found?` terminal implies that the section could be missing during normal operation, which isn't the case.

**Comment by dbendele** [comment]
> @dbendele I do not believe `Find Logging Section.vi` should have a `found?` output. I'm happy to discuss if a better error should be set than just returning an invalid item ref, but having a `found?` terminal implies that the section could be missing during normal operation, which isn't the case.

I don't think any user code should (have to) check the validity of the returned reference. Returning a descriptive error message with steps to resolve is far more important than a **found?** output. Generally, I don't think we provide _Find_ functionality for required sections as the user doesn't/shouldn't have to care about internal structure of system definition.

**Comment by rtzoeller** [comment]
> Generally, I don't think we provide Find functionality for required sections as the user doesn't/shouldn't have to care about internal structure of system definition.

@dbendele R+F and related CDs do, because we needed a way for scripting API users to traverse the system definition to subsections.

How do you propose a user gets a reference to the logging section without this VI?

**Comment by dbendele** [comment]
> > Generally, I don't think we provide Find functionality for required sections as the user doesn't/shouldn't have to care about internal structure of system definition.
> 
> @dbendele R+F and related CDs do, because we needed a way for scripting API users to traverse the system definition to subsections.
> 
> How do you propose a user gets a reference to the logging section without this VI?

**Review by dbendele — APPROVED** [review]

**Pull request merged**
