### PR TITLE
Removed hard coded SSM for BNR and BCD encoded parameters

### LINKED ISSUE #246: Parameters config file: for signed BNR parameters, the SSM bits are always set to "11" during message transmission
When configuring a signed BNR parameter, e.g.:

```
<label>
	<labelDecimal>6</labelDecimal>
	<transferType>0</transferType>
	<parameter>
		<encoding>BNR</encoding>
		<signed>true</signed>
		<startBit>10</startBit>
		<numberOfBits>19</numberOfBits>
		<scale>1.0</scale>
		<offset>0.0</offset>
		<name>Cycle Number</name>
		<defaultValue>0.0</defaultValue>
	</parameter>
</label>
```

the SSM bits (bits 29-30) are always set, ignoring the payload data bits. Is this behaviour intended? how can you change/force the SSM bits to a desired value?

Custom Device Release Version 21.3.0.6

### PR DESCRIPTION
**Pull request by jkreienh**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-ballard-arinc429-custom-device/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Removes the hard coded SSM value that are set based on whether the parameter was signed/unsigned.  Fixes #246 

### Why should this Pull Request be merged?

SSM should not be forced to 00 or 11 based on signed/unsigned parameter values and should be set via a user specified SSM parameter.

### What testing has been done?

Created a SSM parameter on a loopback test and verified proper value updates.

### CODE REVIEW

**Comment by buckd** [comment]
@jkreienh There is also a check of the SSM bits in the BCD case of `Decode Parameter (DBL) from Word.vim`. It looks like this the proposed change without changing this VIM could cause decoding to be incorrect for BCD. Can you verify that?

Also, we have some automated tests that check the validity of the data words when logging is enabled. I don't have access to our system with a Ballard 429 card right now, but if we are not setting the SSM bits anymore, it's very possible these tests will fail. Can you run the automated tests on your target? I've already run the unit tests and they look good, but I suspect it's possible some of the Loopback or Logging tests will fail.

To run these tests on your target, just change the IP address or hostname in`Source\Custom Device Support\Tests\System\<Logging and Single Board> Loopback\targets.ini` to match your system. Then you can run the tests in VI Tester and verify they pass.

**Comment by jkreienh** [comment]
@buckd 
>There is also a check of the SSM bits in the BCD case of `Decode Parameter (DBL) from Word.vim`. It looks like this the proposed change without changing this VIM could cause decoding to be incorrect for BCD. Can you verify that?
> 

I verified that the all enabled VI Tester steps passed after the update to `Decode Parameter (DBL) from Word.vim`.

Updates required to run tests:

  1.  Removed the target password
  2.  Updated the hostname in `Source\Custom Device Support\Tests\System\Logging Loopback\targets.ini` 
  3.  Updated the hostname in `Source\Custom Device Support\Tests\System\Single Board Loopback\targets.ini` 
  4.  Updated the hostname in `Source\Custom Device Support\Tests\System\Development\targets.ini` 
  5.  Wired a direct loopback on Core 0's P2 to P3.
  6.  Updated `Script Custom Device.vi` to use the appropriate slot.  _Default is Slot 2._

**Review by buckd — APPROVED** [review]

**Pull request merged**
